config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'perfil/:id', to: "users#show", as: :perfil

  devise_scope :user do
   get "login" , to: "devise/sessions#new", as: :login
   get "logout" , to: "devise/sessions#destroy", as: :logout
   get "registro" , to: "devise/registrations#new", as: :registro
  end
  resources :todo_lists do
    resources :todo_items do
      patch :complete
    end
  end
  root 'pages#home'
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
	belongs_to :user
	has_many :todo_items
	validates :title, presence: true, length: {minimum: 3}
	validates :description, presence: true, length: {minimum: 7}

	def has_completed_items?
    	todo_items.complete.size > 0
	end

	def has_incomplete_items?
	  	todo_items.incomplete.size > 0
	end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]
  before_action :verify_ownership, only: [:show, :edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = current_user.todo_lists.all
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = TodoList.new(user_id: current_user.id, title: todo_list_params[:title], description: todo_list_params[:description] )

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'La lista ha sido creada satisfactoriamente.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'La lista ha sido actualizada satisfactoriamente.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: 'La lista ha sido eliminada satisfactoriamente.' }
      format.json { head :no_content }
    end
  end

  def verify_ownership
    if @todo_list.user_id != current_user.id
      respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: 'No puede acceder a listas que no le pertenecen' }
      format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
      params.require(:todo_list).permit(:title, :description)
    end
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/todo_lists/_form.html.erb
<%= simple_form_for(@todo_list) do |f| %>
<div class="nospaces">
  <% if @todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_list.errors.count, "errores") %> no han dejado que se pueda guardar correctamente</h2>

      <ul>
      <% @todo_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.input :title %>
  <%= f.input :description%>
  </div>
  <div class="nospaces allright col-xs-4 actions">
    <%= f.button :submit  %>
  </div>
<% end %>

app/views/todo_lists/_info.html.erb
<% if user_signed_in? %>
	<div class="allright nospaces col-xs-12">
		<div class="col-xs-2">
		<img src="<%= current_user.gravatar_url %>"></div>
		<div class="allright nospaces col-xs-9">
			<p><%= current_user.email %></p>
			<%= link_to "Salir #{image_tag('Icons/Quit.png')}".html_safe,logout_path,:style =>"text-decoration: none;" %>
		</div>
	</div>
<%end%>

app/views/todo_lists/edit.html.erb
<h1>Edición Lista</h1>
<%= render 'info' %>
<%= render 'form' %>


<%= link_to 'Show', @todo_list %> |
<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/index.html.erb
<div>
  <div class="nospaces col-xs-12">
    <%= render 'info' %>
  </div>
  <div class="nospaces col-xs-12">
    <div class="nospaces col-xs-8"><h1>Mis Listas</h1></div>
    <div class="allright nospaces col-xs-4" style="padding:10% 0 0 0;"><%= link_to (image_tag "Icons/Add.png"), new_todo_list_path,:id=>"Add"%></div>
  </div>
    <div class="nospaces col-xs-12">
      <% @todo_lists.each do |todo_list| %>
        <div onclick="location.href='<%= todo_list_path(todo_list)%>';" style="cursor: pointer;" id="<%=dom_id(todo_list)%>" class="col-xs-12 well lista">
          <div class="info">
            <strong><%= todo_list.title %></strong>
            <span class="description allright"><% if todo_list.description.length >40%>
                  <%= todo_list.description[0,40]+ " ..." %>
              <%else%>
                  <%= todo_list.description %>
              <%end%></span>
          </div>
        </div>
      <% end %>
    </div>
</div>

app/views/todo_lists/new.html.erb
  <%= render 'info' %>
<div>
	<h1>Nueva Lista</h1>
	<%= render 'form' %>
</div>
<div class="col-xs-12">
	<%= link_to 'Regresar', todo_lists_path %>
</div>

app/views/todo_lists/show.html.erb
<div class="col-xs-12" ><%= render 'info' %></div>

<div class="col-xs-12 encabezado">
		<h1><%= @todo_list.title %></h1>
		<p><strong><%= @todo_list.description %></strong></p>
			<p><%= link_to 'Editar lista', edit_todo_list_path(@todo_list) %> |
				<%= link_to 'Eliminar lista', @todo_list, method: :delete, data: { confirm: '¿Estás seguro de que deseas eliminar esta lista?' } %></p>
</div>
<div  class="col-xs-12">
	<div class="allright">
		<%= link_to (image_tag "Icons/Add.png"), new_todo_list_todo_item_path(@todo_list.id),:id=>"Add" %>
	</div>
</div>
<div class="col-xs-12">
<table  class="table">
	<thead>
	    <tr>
	    	<th style="width:10%;"><h3><strong>Fecha</strong></h3></th>
	    	<th style="width:10%;text-align: center"><h3><strong>Estado</strong></h3></th>
	      	<th style="width:60%;"><h3><strong>Contenido</strong></h3></th>
	      	<th style="width:20%;text-align: center"><h3><strong>Acciones</strong></h3></th>
	    </tr>
	</thead>
	<tbody>
	    <%@todo_list.todo_items.each do |item| %>
	    <tr class="acciones"id= "<%=dom_id(item)%>">
	        <td><p><%= Date.parse(item.created_at.to_s) %></p> </td>
	        <%if item.completed_at.nil? %>
	        <td><%= link_to (image_tag "Icons/Complete.png",:class=>"yet"),todo_list_todo_item_complete_path(@todo_list,item), method: :patch%></td>
	        <%else%>
	        	<td><%=image_tag "Icons/Complete.png" ,:class => "acciones"%></td>
	        <%end%>
	        <td><p><%= item.content %></p>  </td>
	     	<td ><p><%= link_to (image_tag "Icons/Edit.png"), edit_todo_list_todo_item_path(@todo_list,item),:id=>"Edit"%> | <%= link_to (image_tag "Icons/Delete.png"),todo_list_todo_item_path(@todo_list,item),:id=>"Delete", method: :delete, data: { confirm: '¿Estás seguro de que deseas eliminar esta tarea?'}%>
	     	</p> </td>
	     </tr>
		<%end%>
	</tbody>
</table>
</div>